name: foodu_food_delivery_app_ui

description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  font_awesome_flutter: ^10.7.0
  flutter_credit_card: ^4.0.1
  google_fonts: ^6.2.1
  flutter_otp_text_field: ^1.2.0
  country_icons: ^2.0.2
  country_picker: ^2.0.20
  country_code_picker: ^2.0.0
  image_picker: ^0.8.4+2
  lottie: ^2.3.2
  flutter_svg: ^1.1.6
  google_maps_flutter: ^2.2.2
  intl_phone_field: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_spinkit: ^5.1.0
  hexcolor: ^3.0.1
  animated_widgets: ^1.1.0
  get: ^4.6.6
  intl: ^0.18.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/
    - assets/flags/
    - assets/fonts/
    - assets/images/facebook.png